# Generated by Django 4.2 on 2023-04-17 10:10

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrapers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game', models.CharField(choices=[('COUNTER_STRIKE', 'Counter-Strike'), ('LEAGUE_OF_LEGENDS', 'League of Legends'), ('VALORANT', 'Valorant')], max_length=32)),
                ('name', models.CharField(max_length=128)),
                ('logo_filename', models.CharField(max_length=256)),
                ('nationality', models.CharField(max_length=256)),
                ('ranking', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
            ],
        ),
    ]
