# Generated by Django 4.2 on 2023-04-18 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrapers', '0005_alter_scheduledmatch_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scheduledmatch',
            name='type',
        ),
        migrations.AddField(
            model_name='scheduledmatch',
            name='format',
            field=models.CharField(choices=[('BEST_OF_1', 'Bo1'), ('BEST_OF_3', 'Bo3'), ('BEST_OF_5', 'Bo5')], default='BEST_OF_1', max_length=16),
            preserve_default=False,
        ),
    ]
