# Generated by Django 4.2 on 2023-04-18 14:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scrapers', '0006_remove_scheduledmatch_type_scheduledmatch_format'),
    ]

    operations = [
        migrations.RenameField(
            model_name='scheduledmatch',
            old_name='estimated_end_time',
            new_name='estimated_end_datetime',
        ),
        migrations.RenameField(
            model_name='scheduledmatch',
            old_name='start_time',
            new_name='start_datetime',
        ),
    ]
