# Generated by Django 4.2 on 2023-04-18 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrapers', '0009_alter_team_logo_filename_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='url',
            field=models.URLField(blank=True, max_length=128, null=True),
        ),
    ]
