# Generated by Django 4.2 on 2023-04-21 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrapers', '0013_alter_tournament_first_place_prize_us_dollars_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='background_color',
            field=models.CharField(blank=True, max_length=7, null=True),
        ),
    ]
