# Generated by Django 4.2 on 2023-04-22 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrapers', '0015_alter_team_background_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scheduledmatch',
            name='tournament_context',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
