# Generated by Django 4.2 on 2023-04-23 05:47

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scrapers', '0016_alter_scheduledmatch_tournament_context'),
    ]

    operations = [
        migrations.CreateModel(
            name='FinishedMatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scheduled_match', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='scrapers.scheduledmatch')),
            ],
        ),
        migrations.CreateModel(
            name='GameVod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('host', models.CharField(choices=[('YOUTUBE', 'YouTube'), ('TWITCH', 'Twitch')], max_length=16)),
                ('language', models.CharField(max_length=64)),
                ('game_count', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('vod_url', models.URLField(max_length=128)),
                ('vod_filename', models.CharField(max_length=256)),
                ('finished_match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scrapers.finishedmatch')),
            ],
        ),
    ]
