# Generated by Django 4.2 on 2023-04-23 06:50

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrapers', '0018_rename_vod_filename_gamevod_filename_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tournament_context', models.CharField(blank=True, max_length=64, null=True)),
                ('format', models.CharField(choices=[('BEST_OF_1', 'Bo1'), ('BEST_OF_3', 'Bo3'), ('BEST_OF_5', 'Bo5')], max_length=16)),
                ('tier', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('url', models.URLField(max_length=128)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('start_datetime', models.DateTimeField()),
                ('estimated_end_datetime', models.DateTimeField()),
                ('create_video', models.BooleanField()),
                ('finished', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name_plural': 'matches',
            },
        ),
        migrations.RemoveField(
            model_name='scheduledmatch',
            name='team_1',
        ),
        migrations.RemoveField(
            model_name='scheduledmatch',
            name='team_2',
        ),
        migrations.RemoveField(
            model_name='scheduledmatch',
            name='tournament',
        ),
        migrations.RemoveField(
            model_name='gamevod',
            name='finished_match',
        ),
    ]
