# Generated by Django 4.2 on 2023-04-24 09:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scrapers', '0020_delete_scheduledmatch_match_team_1_match_team_2_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GOTVDemo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(max_length=256)),
                ('game_vod', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='scrapers.gamevod')),
            ],
        ),
    ]
