# Generated by Django 4.2 on 2023-05-08 09:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scrapers', '0027_player_team'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamevod',
            name='mvp',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='scrapers.player'),
        ),
        migrations.AddField(
            model_name='match',
            name='mvp',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='scrapers.player'),
        ),
    ]
