# Generated by Django 4.2 on 2023-05-08 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrapers', '0028_gamevod_mvp_match_mvp'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='url',
            field=models.URLField(default='test', max_length=128),
            preserve_default=False,
        ),
    ]
