# Generated by Django 4.2 on 2023-05-08 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrapers', '0030_player_tag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gamevod',
            name='map',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
