# Generated by Django 4.2 on 2023-05-14 07:32

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrapers', '0032_gamevod_game_start_offset'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gamevod',
            name='game_start_offset',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
