# Generated by Django 4.2 on 2023-05-25 23:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scrapers', '0037_remove_match_highlighted_gamevod_highlighted'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='match',
            name='mvp',
        ),
        migrations.RemoveField(
            model_name='match',
            name='team_1_statistics_filename',
        ),
        migrations.RemoveField(
            model_name='match',
            name='team_2_statistics_filename',
        ),
    ]
