# Generated by Django 4.2 on 2023-06-01 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrapers', '0041_gamevod_process_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='stream_url',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
