# Generated by Django 4.2 on 2023-06-04 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrapers', '0045_tournament_display_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='alternate_names',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
