# Generated by Django 4.2 on 2023-04-25 10:17

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('scrapers', '0022_gamevod_team_1_statistics_filename_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Highlight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time_seconds', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('duration_seconds', models.IntegerField(validators=[django.core.validators.MinValueValidator(5)])),
                ('events', models.CharField(max_length=512)),
                ('round_number', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('game_vod', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='scrapers.gamevod')),
            ],
        ),
    ]
