# Generated by Django 4.2 on 2023-04-25 20:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scrapers', '0022_gamevod_team_1_statistics_filename_and_more'),
        ('highlights', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='highlight',
            name='game_vod',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scrapers.gamevod'),
        ),
    ]
