# Generated by Django 4.2 on 2023-04-20 19:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('scrapers', '0013_alter_tournament_first_place_prize_us_dollars_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='VideoMetadata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField(max_length=5000)),
                ('tags', models.JSONField()),
                ('thumbnail_filename', models.CharField(max_length=256)),
                ('language', models.CharField(default='english', max_length=256)),
                ('category_id', models.IntegerField(default=20)),
                ('scheduled_match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scrapers.scheduledmatch')),
            ],
        ),
    ]
