# Generated by Django 4.2 on 2023-04-23 06:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scrapers', '0019_match_remove_scheduledmatch_team_1_and_more'),
        ('videos', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='videometadata',
            name='scheduled_match',
        ),
        migrations.AddField(
            model_name='videometadata',
            name='match',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='scrapers.match'),
            preserve_default=False,
        ),
    ]
