# Generated by Django 4.2 on 2023-05-03 19:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scrapers', '0024_gamevod_round_count'),
        ('videos', '0002_remove_videometadata_scheduled_match_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videometadata',
            name='match',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='scrapers.match'),
        ),
    ]
