# Generated by Django 4.2 on 2023-04-17 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrapers', '0003_scheduledmatch'),
    ]

    operations = [
        migrations.AddField(
            model_name='scheduledmatch',
            name='create_video',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='team',
            name='url',
            field=models.URLField(default='www.test.com', max_length=128),
            preserve_default=False,
        ),
    ]
