# Generated by Django 4.2 on 2023-04-18 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrapers', '0007_rename_estimated_end_time_scheduledmatch_estimated_end_datetime_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tournament',
            name='url',
            field=models.URLField(blank=True, max_length=128, null=True),
        ),
    ]
