# Generated by Django 4.2 on 2023-04-18 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrapers', '0008_alter_tournament_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='logo_filename',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='logo_filename',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
