# Generated by Django 4.2 on 2023-04-18 20:19

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrapers', '0010_alter_team_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='nationality',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='team',
            name='ranking',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
