# Generated by Django 4.2 on 2023-04-21 14:35

import colorfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scrapers', '0014_team_background_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='background_color',
            field=colorfield.fields.ColorField(blank=True, default=None, image_field=None, max_length=18, null=True, samples=None),
        ),
    ]
