# Generated by Django 4.2 on 2023-04-24 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrapers', '0021_gotvdemo'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamevod',
            name='team_1_statistics_filename',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='gamevod',
            name='team_2_statistics_filename',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='match',
            name='team_1_statistics_filename',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='match',
            name='team_2_statistics_filename',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
