# Generated by Django 4.2 on 2023-04-26 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrapers', '0022_gamevod_team_1_statistics_filename_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='highlighted',
            field=models.BooleanField(default=False),
        ),
    ]
