# Generated by Django 4.2 on 2023-05-02 08:01

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrapers', '0023_match_highlighted'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamevod',
            name='round_count',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(16)]),
            preserve_default=False,
        ),
    ]
