# Generated by Django 4.2 on 2023-05-08 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrapers', '0025_remove_gamevod_round_count_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('nationality', models.CharField(max_length=128)),
                ('profile_picture_filename', models.CharField(blank=True, max_length=256, null=True)),
            ],
        ),
    ]
