# Generated by Django 4.2 on 2023-05-08 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrapers', '0029_player_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='tag',
            field=models.CharField(default='test', max_length=128),
            preserve_default=False,
        ),
    ]
