# Generated by Django 4.2 on 2023-05-14 07:31

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrapers', '0031_alter_gamevod_map'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamevod',
            name='game_start_offset',
            field=models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(0)]),
            preserve_default=False,
        ),
    ]
