# Generated by Django 4.2 on 2023-05-25 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrapers', '0034_organization_remove_team_background_color_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamevod',
            name='finished',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='gamevod',
            name='highlighted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='gamevod',
            name='start_datetime',
            field=models.DateTimeField(default="2022-10-10 00:00"),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='gamevod',
            name='filename',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
