# Generated by Django 4.2 on 2023-05-25 21:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scrapers', '0035_gamevod_finished_gamevod_highlighted_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gamevod',
            name='highlighted',
        ),
    ]
