# Generated by Django 4.2 on 2023-05-26 09:08

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrapers', '0038_remove_match_mvp_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gamevod',
            name='team_1_round_count',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='gamevod',
            name='team_2_round_count',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='gamevod',
            name='url',
            field=models.URLField(blank=True, max_length=128, null=True),
        ),
    ]
