# Generated by Django 4.2 on 2023-05-31 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrapers', '0039_alter_gamevod_team_1_round_count_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gamevod',
            name='start_datetime',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
