# Generated by Django 4.2 on 2023-06-04 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrapers', '0044_organization_display_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='display_name',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
